### ISSUE TITLE
Draft on the system design

### ISSUE THREAD

**Issue by mr9dollars** [oursky/skygear-rbac#1]

**Comment by IniZio** [comment]
1. Since this is a skygear gear, should it also cover per-rescord ACL in skygear v1?
2. There will need to be a function which accepts the verified user id and resource id and return the whole user profile and resource info, where should it be done?

**Comment by mr9dollars** [comment]
@rickmak @IniZio  What is the status of this issue?

**Comment by jimmywongz** [comment]
@limouren @IniZio @limouren What is the situation of this issue?

**Comment by jimmywongz** [comment]
@mr9dollars Please help to follow up, thanks

**Comment by mr9dollars** [comment]
new issue will be open by @IniZio base on oursky/skygear-rbac#2. I will archive this
