### ISSUE TITLE
Write sensible db adaptor that allows custom db name thus works with non-admin user

### ISSUE THREAD

**Issue by rickmak** [oursky/skygear-rbac#18]
- [ ] Use a flag to disable attempting to create table
- [ ] Allow custom db name

**Comment by limouren** [comment]
Out of my scope, cannot provide estimation.

**Comment by mr9dollars** [comment]
what is the use of this one.. If urgent we should sort this out @@

**Comment by rickmak** [comment]
Not urgent, but need to do before production deployment.

**Comment by jimmywongz** [comment]
Please help to handle, will deploy production next sprint

**Comment by mr9dollars** [comment]
@rickmak has to handle before deploy production right?

**Comment by rickmak** [comment]
I think yes, but @cychiuae decide.

**Comment by cychiuae** [comment]
https://github.com/cychiuae/casbin-pg-adapter
